## Linear Function

In [ ]:
import torch
import torch.nn as nn
import numpy as np

# Linear Function
# input dim = 5, output dim = 1
linear = nn.Linear(5, 1)
x = torch.FloatTensor([-2, -1, 0, 1, 2])
print(linear(x)) 
print(linear.parameters())

## Activation Function

In [1]:
x = torch.FloatTensor([-2, -1, 0, 1, 2])
print(x)

# ReLU
relu = nn.ReLU()
print(relu(x)) 

# Sigmoid
sigmoid = nn.Sigmoid()
print(sigmoid(x))

# Tanh
tanh = nn.Tanh()
print(tanh(x))

# Softmax
softmax = nn.Softmax(dim = 0)
print(softmax(x))

tensor([ 2.2133, -0.1138,  1.5308, -0.7443,  0.3721])
tensor([2.2133, 0.0000, 1.5308, 0.0000, 0.3721])
tensor([0.9014, 0.4716, 0.8221, 0.3221, 0.5920])
tensor([ 0.9764, -0.1133,  0.9106, -0.6318,  0.3558])
tensor([0.5514, 0.0538, 0.2787, 0.0286, 0.0875])


## Loss Function

In [2]:
a = torch.FloatTensor([1, 4, 2])
b = torch.FloatTensor([1, 3, 2])

# MSE Loss
mse = nn.MSELoss()
print(mse(a, b))

tensor(0.3333)


In [5]:
a = torch.FloatTensor([[1, 4, 2], [0.5, 0.3, 0.2]])
b = torch.LongTensor([0, 0])

cross_entropy = nn.CrossEntropyLoss()
print(cross_entropy(a,b))

tensor(2.0548)


## Convolutional Neural Network

In [4]:
import torch
import torch.nn as nn
import torch.optim as optim

from torch.autograd import Variable
from torch.utils.data import DataLoader
from torchvision import transforms
from torchvision import datasets

batch_size = 32
learning_rate = 0.01
num_epochs = 5

# MNIST Dataset DataLoader
train_dataset = datasets.MNIST(root='./data', train=True,
                        transform=transforms.ToTensor(), download=True)
test_dataset = datasets.MNIST(root='./data', train=False,
                        transform=transforms.ToTensor())

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

Processing...
Done!


In [21]:
class CNN(nn.Module):
    def __init__(self, num_classes=10):
        super(CNN, self).__init__()
        self.layer1 = nn.Sequential(
            nn.Conv2d(1, 16, kernel_size=5, stride=1, padding=2),
            nn.BatchNorm2d(16),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2))
        self.layer2 = nn.Sequential(
            nn.Conv2d(16, 32, kernel_size=5, stride=1, padding=2),
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2))
        self.fc = nn.Linear(7*7*32, num_classes)
        
    def forward(self, x):
        out = self.layer1(x)
        out = self.layer2(out)
        out = out.view(out.size(0), -1)
        out = self.fc(out)
        
        return out

In [22]:
# Model
model = CNN()

# Loss
criterion = nn.CrossEntropyLoss()

# Optimizer
optimizer = optim.SGD(model.parameters(), lr=learning_rate)

In [23]:
# Traing the model
for epoch in range(num_epochs):
    for i, (img, label) in enumerate(train_loader, 1):
        img, label = Variable(img), Variable(label)
        out = model(img)
        loss = criterion(out, label)
        
        # Backward and optimize
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        if (i+1) % 100 == 0:
            print('Epoch [{}/{}], Step [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, i+1, len(train_loader), loss.item()))

Epoch [1/5], Step [100/1875], Loss: 0.7248
Epoch [1/5], Step [200/1875], Loss: 0.2679
Epoch [1/5], Step [300/1875], Loss: 0.2180
Epoch [1/5], Step [400/1875], Loss: 0.3786
Epoch [1/5], Step [500/1875], Loss: 0.1143
Epoch [1/5], Step [600/1875], Loss: 0.1453
Epoch [1/5], Step [700/1875], Loss: 0.2521
Epoch [1/5], Step [800/1875], Loss: 0.0984
Epoch [1/5], Step [900/1875], Loss: 0.2446
Epoch [1/5], Step [1000/1875], Loss: 0.0408
Epoch [1/5], Step [1100/1875], Loss: 0.1056
Epoch [1/5], Step [1200/1875], Loss: 0.0450
Epoch [1/5], Step [1300/1875], Loss: 0.2596
Epoch [1/5], Step [1400/1875], Loss: 0.1380
Epoch [1/5], Step [1500/1875], Loss: 0.2578
Epoch [1/5], Step [1600/1875], Loss: 0.0182
Epoch [1/5], Step [1700/1875], Loss: 0.1190
Epoch [1/5], Step [1800/1875], Loss: 0.3783
Epoch [2/5], Step [100/1875], Loss: 0.0690
Epoch [2/5], Step [200/1875], Loss: 0.1108
Epoch [2/5], Step [300/1875], Loss: 0.1454
Epoch [2/5], Step [400/1875], Loss: 0.1535
Epoch [2/5], Step [500/1875], Loss: 0.0612
Ep

In [24]:
# Test the model
model.eval()

correct = 0
total = 0
for img, label in test_loader:
    out = model(img)
    _, predicted = torch.max(out.data, 1)
    total += label.size(0)
    correct += (predicted == label).sum().item()
    
print('Test Accuracy of the model on the 10000 test images: {} %'.format(100 * correct / total))

# Save the model checkpoint
torch.save(model.state_dict(), 'model_nn.ckpt')

Test Accuracy of the model on the 10000 test images: 98.73 %


### 과제. Neural Network에 활성함수 & BatchNorm 추가

In [ ]:
# Neural Network는 저번 코드 참고


### 과제. CIFAR-10 Dataset에 CNN 구현
Hint. CIFAR-10의 크기는 32x32x3 & Class는 10개

In [25]:
import torch
import torch.nn as nn
import torch.optim as optim

from torch.autograd import Variable
from torch.utils.data import DataLoader
from torchvision import transforms
from torchvision import datasets

batch_size = 4
learning_rate = 0.01
num_epochs = 5

# CIFAR-10 Dataset DataLoader
trainset = datasets.CIFAR10(root='./data', train=True, download=True,
                                        transform=transforms.ToTensor())

testset = datasets.CIFAR10(root='./data', train=False, download=True, 
                                       transform=transforms.ToTensor())


train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

Files already downloaded and verified
