In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
e0 = [0.1, 0.2, 0.3] # 매우
e1 = [0.2, 0.3, 0.4] # 재밌는
e2 = [0.3, 0.4, 0.5] # 딥러닝
e3 = [0.4, 0.5, 0.6] # 시간

embedding_matrix = torch.Tensor([e0, e1, e2, e3])

seq = ["매우", "재밌는", "딥러닝", "시간"]
seq_ix = [0, 1, 2, 3]

In [3]:
batch_size = 1

embed = embedding_matrix[0:4]
embed_concat = embed.reshape(batch_size,1, -1)
embed_concat

tensor([[[ 0.1000,  0.2000,  0.3000,  0.2000,  0.3000,  0.4000,  0.3000,
           0.4000,  0.5000,  0.4000,  0.5000,  0.6000]]])

In [4]:
in_channels = 1 # only text >> always 1
out_channels = 30 # Hyperparameter
filter_sizes = [3, 4, 5]
embed_size = embedding_matrix.size(1)

In [5]:
# -1로 weight initialization
custom_kernel_weight = torch.Tensor([-1]*embed_size*filter_sizes[0]).reshape(1,1,-1)

conv_out = F.conv1d(embed_concat, custom_kernel_weight)
print(conv_out.size())
print(conv_out[0])

torch.Size([1, 1, 4])
tensor([[-2.7000, -3.0000, -3.3000, -3.6000]])


In [10]:

custom_kernel_weight = torch.Tensor([-1, 0, 0.1, 0.2, 0.5, 0, 0, 1, 1]).reshape(1,1,-1)

conv_out = F.conv1d(embed_concat, custom_kernel_weight)
print(conv_out.size())
print(conv_out[0])

torch.Size([1, 1, 4])
tensor([[ 1.0200,  0.9800,  0.8600,  1.2000]])


In [14]:
torch.tanh(torch.Tensor([[1.02, 0.98, 0.86, 1.20]]))

tensor([[ 0.7699,  0.7531,  0.6963,  0.8337]])